### ISSUE TITLE
Decay scaled affinities for DYNAMITE analysis

### ISSUE THREAD

**Issue by juhomon** [SchulzLab/TEPIC#32]
Hi,

is it generally okay to use decay scaled affinity values for DYNAMITE-analysis? I'm just wondering this because these values are currently unsupported in the computeMeanRatioTFAffinities.py script. I'm currently using TEPIC with following parameters to produce these files:

TEPIC/Code/TEPIC.sh \
		-g $genomefasta \
		-b $outSorted1 \
		-o $cond1 \
		-p $PSEMfile \
		-a $GTFfile \
		-w 3000 \
		-e TRUE \
		-n 4 \
		-c 20 \
		-m $PSEMLfile \
		-u \
		-x \
		-v 0.05 \
		-r $Twobitfile

So I get "_Prefix__Decay_Scaled_Affinity_Gene_View_Filtered.txt" files for each of the groups. I have currently modified the computeMeanRatioTFAffinities.py to accept these files but before I continue further with the results I would just like to have confirmation from you that this is a valid approach.

Thank you even beforehand!
Juho

**Comment by SchulzLab** [comment]
Hi Juho,
I am not aware that we have tried that. If you scale the TF affinity in a peak/footprint with the average signal of the peak, then you need to make sure that the average signal values between your different replicates in case/control are depth normalised ( I mean for differences in sequencing depth in those different replicates). Otherwise, you may get artefacts in the feature selection step.

But it would be worthwhile to test what the difference is in performance between using scaling or not.

Hope that helps,
Marcel

**Comment by juhomon** [comment]
Hi,

I've been using VST counts from DESeq2 for the signal. I'll keep on working with the analysis and try out different settings. Thank you for the quick answer and the pipeline!

J
